import { Transaction, CreditEntry, DailySummary, ChatMessage } from '@/types/bizplus';

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    type: 'income',
    amount: 2500,
    method: 'mpesa',
    description: 'Payment from John Mwangi',
    date: new Date(),
    mpesaCode: 'QJK2L5M8N9',
    customerName: 'John Mwangi',
  },
  {
    id: '2',
    type: 'income',
    amount: 1800,
    method: 'cash',
    description: 'Shop sales',
    date: new Date(),
    category: 'Sales',
  },
  {
    id: '3',
    type: 'expense',
    amount: 500,
    method: 'mpesa',
    description: 'Electricity token',
    date: new Date(),
    mpesaCode: 'QJK2L5M8P0',
    category: 'Utilities',
  },
  {
    id: '4',
    type: 'income',
    amount: 3200,
    method: 'mpesa',
    description: 'Payment from Mary Wanjiku',
    date: new Date(),
    mpesaCode: 'QJK2L5M8Q1',
    customerName: 'Mary Wanjiku',
  },
  {
    id: '5',
    type: 'expense',
    amount: 1200,
    method: 'cash',
    description: 'Stock purchase',
    date: new Date(),
    category: 'Inventory',
  },
  {
    id: '6',
    type: 'income',
    amount: 4500,
    method: 'mpesa',
    description: 'Wholesale order',
    date: new Date(Date.now() - 86400000),
    mpesaCode: 'QJK2L5M8R2',
  },
  {
    id: '7',
    type: 'income',
    amount: 800,
    method: 'cash',
    description: 'Morning sales',
    date: new Date(Date.now() - 86400000),
  },
];

export const mockCredits: CreditEntry[] = [
  {
    id: '1',
    customerName: 'Mary Wanjiku',
    phoneNumber: '0712345678',
    amount: 2000,
    description: 'Goods on credit',
    date: new Date(Date.now() - 604800000),
    dueDate: new Date(Date.now() + 604800000),
    status: 'pending',
    payments: [],
  },
  {
    id: '2',
    customerName: 'Peter Kamau',
    phoneNumber: '0723456789',
    amount: 3500,
    description: 'Construction materials',
    date: new Date(Date.now() - 1209600000),
    status: 'partial',
    payments: [
      { id: '1', amount: 1500, date: new Date(Date.now() - 604800000), method: 'mpesa' },
    ],
  },
  {
    id: '3',
    customerName: 'Jane Njeri',
    phoneNumber: '0734567890',
    amount: 1500,
    description: 'Weekly supplies',
    date: new Date(Date.now() - 172800000),
    dueDate: new Date(Date.now() + 432000000),
    status: 'pending',
    payments: [],
  },
];

export const mockDailySummaries: DailySummary[] = [
  {
    date: new Date(),
    totalSales: 7500,
    totalExpenses: 1700,
    netProfit: 5800,
    mpesaSales: 3200,
    cashSales: 1800,
    pochiSales: 2500,
    expectedCash: 600,
    transactionCount: 5,
  },
  {
    date: new Date(Date.now() - 86400000),
    totalSales: 5300,
    totalExpenses: 2100,
    netProfit: 3200,
    mpesaSales: 2500,
    cashSales: 800,
    pochiSales: 2000,
    expectedCash: 800,
    actualCash: 750,
    variance: -50,
    transactionCount: 8,
  },
  {
    date: new Date(Date.now() - 172800000),
    totalSales: 8200,
    totalExpenses: 1500,
    netProfit: 6700,
    mpesaSales: 3500,
    cashSales: 2200,
    pochiSales: 2500,
    expectedCash: 2200,
    actualCash: 2200,
    variance: 0,
    transactionCount: 12,
  },
];

export const mockChatMessages: ChatMessage[] = [
  {
    id: '1',
    type: 'received',
    content: 'QJK2L5M8N9 Confirmed. You have received Ksh2,500.00 from JOHN MWANGI 0712345678 on 28/1/25 at 2:30 PM. New M-PESA balance is Ksh15,200.00.',
    timestamp: new Date(Date.now() - 3600000),
    parsed: {
      transactionCode: 'QJK2L5M8N9',
      amount: 2500,
      type: 'received',
      party: 'JOHN MWANGI',
      date: new Date(),
      balance: 15200,
    },
  },
  {
    id: '2',
    type: 'system',
    content: '✅ Transaction logged: KES 2,500 received from John Mwangi',
    timestamp: new Date(Date.now() - 3590000),
  },
  {
    id: '3',
    type: 'received',
    content: 'QJK2L5M8P0 Confirmed. Ksh500.00 paid to KPLC PREPAID. on 28/1/25 at 3:15 PM. New M-PESA balance is Ksh14,700.00.',
    timestamp: new Date(Date.now() - 1800000),
    parsed: {
      transactionCode: 'QJK2L5M8P0',
      amount: 500,
      type: 'sent',
      party: 'KPLC PREPAID',
      date: new Date(),
      balance: 14700,
    },
  },
  {
    id: '4',
    type: 'system',
    content: '💸 Expense logged: KES 500 paid to KPLC PREPAID',
    timestamp: new Date(Date.now() - 1790000),
  },
];

export const weeklyData = [
  { day: 'Mon', sales: 4200, expenses: 1200 },
  { day: 'Tue', sales: 5800, expenses: 800 },
  { day: 'Wed', sales: 3500, expenses: 1500 },
  { day: 'Thu', sales: 7200, expenses: 2000 },
  { day: 'Fri', sales: 8500, expenses: 1800 },
  { day: 'Sat', sales: 9200, expenses: 2200 },
  { day: 'Sun', sales: 6100, expenses: 900 },
];
